### ISSUE TITLE
APPID issue

### ISSUE THREAD

**Issue by Muhammad-Ullah** [netless-io/Whiteboard-Flutter#7]
Where can I get APP_ID for this app?
You have used "283/VGiScM9Wiw2HJg" but where can I get this one?

**Comment by 27ksandip** [comment]
ya same problem here @buhe @aderan @aderan @alwaysmavs @leavesster 
Where can i get app_id

**Comment by leavesster** [comment]
@27ksandip @Muhammad-Ullah 
You need register a agora account to get App ID. Here is agora's document : [interactive-whiteboard](https://docs.agora.io/en/interactive-whiteboard/overview/core-concepts?platform=android)

**Comment by gopal-cis** [comment]
I/flutter (26373): [InAppWebView] consoleMessage [White] join room fail
I/flutter (26373): [InAppWebView] consoleMessage [White] Error: connect failed: room "076ef9b0b8dd11ed85245975e226531a" not found

**Comment by leavesster** [comment]
> I/flutter (26373): [InAppWebView] consoleMessage [White] join room fail I/flutter (26373): [InAppWebView] consoleMessage [White] Error: connect failed: room "076ef9b0b8dd11ed85245975e226531a" not found

use your own white room uuid and set the right region which you request to whiteboard server.
this issue will be closed to avoid no relation issue report, please open a issue if you have different issues
