### ISSUE TITLE
I have created  room and roomtoken and pass in our code still facing this issue  

### ISSUE THREAD

**Issue by gopal-cis** [netless-io/Whiteboard-Flutter#8]
I have created  room and roomtoken and pass in our code still facing this issue  

I/flutter (26373): [InAppWebView] consoleMessage [White] join room fail
I/flutter (26373): [InAppWebView] consoleMessage [White] Error: connect failed: room "076ef9b0b8dd11ed85245975e226531a" not found

**Comment by leavesster** [comment]
check your request params body. Whiteboard room uuid is isolated between different regions.

**Comment by leavesster** [comment]
We have checked the backend data and confirmed that the room is located in the US region. Therefore, when joining the room, please configure the 'us-sv' region accordingly. You can refer to the SDK's region-related API for more details.
